version: '2.1'


services:
    nginx-proxy:
        image: jwilder/nginx-proxy
        container_name: nginx-proxy
        restart: always
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - /nfs/gitlab/certs:/etc/nginx/certs
            - /var/run/docker.sock:/tmp/docker.sock:ro
    gitlab:
        image: gitlab/gitlab-ee:latest
        container_name: gitlab
        hostname: git.elica.io
        restart: always
        ports:
            - "22:22"
        healthcheck:
            test: ["CMD-SHELL", "curl --fail http://localhost/-/readiness || exit 1"]
            interval: 1m30s
            timeout: 10s
            retries: 3
        volumes:
            - /nfs/gitlab/logs:/var/log/gitlab
            - /nfs/gitlab/config:/etc/gitlab
            - /nfs/gitlab/data:/var/opt/gitlab
            - /nfs/gitlab/certs:/certs
            - /nfs/registry:/registry
        environment:
            - VIRTUAL_HOST=registry.elica.io, git.elica.io
            - VIRTUAL_PORT=80