# pipeline:
#   build:
#       image: plugins/docker
#       username: ${DOCKER_USER}
#       password: ${DOCKER_PASS}
#       email: ${DOCKER_EMAIL}
#       repo: r1cebank/elica-services-weather
#       tags:
#           - latest
#           - ${DRONE_COMMIT_SHA}
#   deploy:
#       image: peloton/drone-rancher
#       url: https://rancher.elica.io
#       access_key: ${RANCHER_ACCESS_KEY}
#       secret_key: ${RANCHER_SECRET_KEY}
#       service: elica-services/elica-services-weather
#       docker_image: r1cebank/elica-services-weather
#   notify:
#       image: plugins/slack
#       webhook: ${SLACK_HOOK}
#       recipient: r1cebank
#       username: drone
#       icon_url: https://avatars0.githubusercontent.com/u/2181346?v=3&s=200
#       when:
#           status: [ success, failure ]
